spring.datasource.url=jdbc:postgresql://localhost:5432/acebook_springboot_test
spring.datasource.username=
spring.datasource.password=
flyway.baseline-on-migrate=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

OKTA_ISSUER=https://dev-jqf4olw6v4md12ul.us.auth0.com/
OKTA_CLIENT_ID=SdwJeBlA9ehSbaqBCVTvEwKdXrrTpCYr
OKTA_CLIENT_SECRET=tvxZBZc4HU9WOUpWS4dAh5PhnalidKlq4mBuH6dsXrahLyKTBCKNKs6LL_OHQ0ci
